### ISSUE TITLE
PhantomJS-rendered PDFs are entirely raster, including the text

### ISSUE THREAD

**Issue by orospakr** [Seldaek/slippy#6]
Normally when I print to PDF from a webkit-based browser, I get a PDF with text that will zoom to any size, and is selectable.

**Comment by abecks** [comment]
@Seldaek What about that commit skips the rasterization process in PhantomJS? I can't find any documentation on it anywhere. Is it because you are setting paperSize?

Im having a similar issue using [node-webshot](https://github.com/brenden/node-webshot), which wraps PhantomJS. All of the PDFs I generate are fully rasterized without selectable text.

**Comment by Seldaek** [comment]
@abecks my problem IIRC was that I output all pages to png first and then combined them into a pdf, and the fix was to output pdfs only and then glue them together as one pdf using pdftk. Good luck :/
